version: '3.8'

services:
  app:
    build: .
    container_name: express_app
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped

volumes:
  pgdata: 