services:
  app:
    build: .
    container_name: express_app
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: .
    volumes:
      - ./google-credentials:/app/google-credentials:ro
    env_file:
      - .env

volumes:
  pgdata:

networks:
  app-network: 