services:
  app:
    build: .
    container_name: express_app
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network
    command: npm run start # 여기서 prisma migrate 제거

  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: .
    volumes:
      - ./google-credentials:/app/google-credentials:ro
    env_file:
      - .env

  migrate:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV:-development}
    command: >
      sh -c "
        if [ \"$NODE_ENV\" = \"production\" ]; then
          npx prisma migrate deploy
        else
          npx prisma migrate reset --force && npx prisma migrate dev --name init
        fi
      "
    networks:
      - app-network
    restart: "no"

volumes:
  pgdata:

networks:
  app-network:
