http:
  routers:
    options-router:
      entryPoints:
        - web
      rule: "Host(`api.${DOMAIN}`) && Method(OPTIONS)"
      service: noop
      middlewares:
        - cors
      priority: 100

    redirect-router:
      entryPoints:
        - web
      rule: "Host(`api.${DOMAIN}`)"
      middlewares:
        - redirect-to-https
      service: noop
      priority: 10

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    cors:
      headers:
        accessControlAllowMethods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        accessControlAllowHeaders: "Content-Type,Authorization,x-trace-id"
        accessControlAllowOriginList: "https://${DOMAIN}://localhost:5173"
        accessControlAllowCredentials: true
        addVaryHeader: true

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"
