# Traefik 정적 설정

# API 및 대시보드 활성화
api:
  dashboard: true
  insecure: true

# 진입점(EntryPoints) 설정
entryPoints:
  web:
    address: ":80"
    # 80 포트로 들어온 모든 요청을 443(https)으로 리디렉션
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# 프로바이더 설정 (Docker 사용)
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# Let's Encrypt 인증서 발급자 설정
certificatesResolvers:
  myresolver:
    acme:
      email: "${LETSENCRYPT_EMAIL}" # .env 변수 사용
      storage: "/etc/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

# 로그 및 트레이싱 설정
log:
  level: INFO
tracing:
  otlp:
    http:
      endpoint: "http://jaeger:4318/v1/traces"
      dialTimeout: 10s # 'timeout' 대신 'dialTimeout' 사용

# 메트릭 설정 (Prometheus)
metrics:
  prometheus:
    addEntryPointsLabels: true

# 액세스 로그 설정
accessLog:
  format: json
