{
 "title": "Demo1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis 메모리",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Express",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres 연결 수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"postgres_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node.js Heap",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " nodejs_heap_size_used_bytes / 1024 / 1024",
     "legendFormat": "Node.js Heap 사용량"
    }
   ]
  },
  {
   "title": "System Resource",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU사용률"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "메모리 사용률"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/rootfs\"}) * 100)",
     "legendFormat": "디스크 사용률"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[5m]) + rate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])",
     "legendFormat": "네트워크 트래픽"
    }
   ]
  },
  {
   "title": "Docker 컨테이너 상태",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/docker/.*\"} / 1024 / 1024",
     "legendFormat": "컨테이너 메모리 사용량"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[5m]) * 100",
     "legendFormat": "컨테이너 CPU 사용률"
    }
   ]
  }
 ]
}