on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ GCP 인증
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ✅ gcloud CLI 설치
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: latest

      # ✅ Compute Engine에 파일 복사
      - name: Copy files to GCP VM
        run: |
          gcloud compute scp \
            --zone ${{ secrets.GCP_ZONE }} \
            docker-compose.prod.yml docker-compose.monitoring.yml docker.sh \
            ${{ secrets.GCP_INSTANCE_NAME }}:~/

      # ✅ SSH 접속 후 배포 명령 실행
      - name: Deploy via gcloud ssh
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone ${{ secrets.GCP_ZONE }} \
            --command "
              docker-compose -f docker-compose.prod.yml pull && \
              docker-compose -f docker-compose.monitoring.yml pull && \
              docker-compose -f docker-compose.prod.yml up -d && \
              docker-compose -f docker-compose.monitoring.yml up -d && \
              docker system prune -af
            "
