name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 1. GCP 인증 (service account JSON)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ✅ 2. gcloud CLI 설치
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: latest

      # ✅ 3. Docker 인증 (GCR 사용 시)
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker asia.gcr.io

      # ✅ 4. 배포 스크립트 실행
      - name: Deploy to Compute Engine
        run: |
          # SSH 키 설정
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ./gcp_ssh_key
          chmod 600 ./gcp_ssh_key
          
          # GCP 인스턴스 IP 가져오기
          INSTANCE_IP=$(gcloud compute instances describe ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone ${{ secrets.GCP_ZONE }} \
            --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          echo "Instance IP: $INSTANCE_IP"

          # 파일 복사
          scp -i ./gcp_ssh_key -o StrictHostKeyChecking=no \
            docker-compose.prod.yml docker-compose.monitoring.yml \
            ${{ secrets.GCP_USERNAME }}@$INSTANCE_IP:~/

          # SSH 접속 후 배포 실행
          ssh -i ./gcp_ssh_key -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@$INSTANCE_IP '
            docker-compose -f docker-compose.prod.yml pull && \
            docker-compose -f docker-compose.monitoring.yml pull && \
            docker-compose -f docker-compose.prod.yml up -d && \
            docker-compose -f docker-compose.monitoring.yml up -d && \
            docker system prune -af
          '

          # SSH 키 삭제
          rm ./gcp_ssh_key
