name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        if: github.ref == 'refs/heads/main'
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:${IMAGE_TAG} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:${IMAGE_TAG} ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:latest
          
          # main 브랜치인 경우 main 태그 추가
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:${IMAGE_TAG} ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:main
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:main
          fi
          
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:latest
