name: CI

on:
  push:
    branches:
      - develop # 메인 브렌치에 브랜치 머지 시 자동으로 실행
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on : ubuntu-latest

    steps:
     - uses : actions/checkout@v4

     - name: login to docker
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

     - name : build dockerfile
       env:
        #DOCKER_IMAGE_TAG: ${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}
       run: docker build -t ${{baikhyunjun}}/도커허브 레퍼지토리 이름
            docker push ${{baikhyunjun}}/도커허브 래퍼지토리 이름  


#도커로 로그인 후 빌드 후 푸시까지
#도커 래퍼지토리 이름 추가 예정
#마지막 run 코드 수정 필요?
